### ISSUE TITLE
Latest release 1.0.1 has wrong version info

### ISSUE THREAD

**Issue by XDelta** [LeCloutPanda/DefaultLaserState#1]
1.0.1 release has the Version 1.0.0 along with `AssemblyFileVersion` and `AssemblyVersion` are both set to 1.0.0.0

**Comment by LeCloutPanda** [comment]
I think it is fixed but ¯\_(ツ)_/¯. gotta keep that in mind for next time.

**Comment by XDelta** [comment]
https://github.com/LeCloutPanda/DefaultLaserState/blob/dfeca46b9981bd71aaacb0091a4d252417ebed78/Patch.cs#L11 shows 1.0.0, but it was changed atleast in the release.
